### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by bat-glitch** [Breq16/flask-discord-interactions#91] opened 2022-05-18 00:01 UTC
Hey,
I keep receiving this error, every time I use `discord.update_commands()`. 
````
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://discord.com/api/v9/oauth2/token

**Comment by Breq16** [comment] 2022-05-21 00:23
Thanks for taking the time to file an issue!

I haven't experienced that yet, it seems surprising that you would end up hitting the rate limit for the token (since the app should only request a new token when the previous one is about to expire). Were you running multiple instances of your bot, or restarting your program repeatedly without waiting?

Discord doesn't include the rate limit information headers on the `/oauth2/token` route, which makes avoiding 429s tricky. I'd like to at least show a more informative warning when this happens, though.

**Comment by bat-glitch** [comment] 2022-05-21 04:22
> Thanks for taking the time to file an issue!
> 
> I haven't experienced that yet, it seems surprising that you would end up hitting the rate limit for the token (since the app should only request a new token when the previous one is about to expire). Were you running multiple instances of your bot, or restarting your program repeatedly without waiting?
> 
> Discord doesn't include the rate limit information headers on the `/oauth2/token` route, which makes avoiding 429s tricky. I'd like to at least show a more informative warning when this happens, though.

It ended up just fixing itself, I don't know why this was happened at-least I'm good for now.

**Comment by bat-glitch** [comment] 2022-05-25 22:40
This happened again, is there anything I could do?

**Comment by Breq16** [comment] 2022-05-26 22:29
Do you have any more information about what triggered the issue? It's hard to troubleshoot something that I'm not able to reproduce.

**Comment by Breq16** [comment] 2022-07-10 20:11
Closing this for now, feel free to reopen if the issue repeats itself or if you have more information that could help diagnose this.

**Closed by Breq16** 2022-07-10 20:11 UTC
Labels: bug
